name: CI/CD Pipeline
on: [push]

env:
  LOG_FILE: /tmp/log.txt

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build Docker image
      shell: bash
      run: |
        echo "Starting building..." >> $env:LOG_FILE
        docker build -t test-nginx:${{ github.run_id }} .
        echo "Building Successfully!" >> $env:LOG_FILE
        docker images >> $env:LOG_FILE

    - name: Upload log file
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: ${{ env.LOG_FILE }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download build logs
      uses: actions/download-artifact@v4
      with:
        name: build-logs
        path: ./

    - name: Deploy to Kubernetes
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        echo "Deploying application..." >> $env:LOG_FILE
        kubectl config use-context microk8s
        kubectl apply -n proj1 -f ./deploy.yaml
        kubectl apply -n proj1 -f ./ingress.yaml
        kubectl apply -n proj1 -f ./service.yaml
        kubectl set image -n proj1 deployment/nginx-deployment nginx=test-nginx:${{ github.run_id }}
        echo "Application successfully deployed." >> $env:LOG_FILE
        type $env:LOG_FILE
