name: CI/CD Pipeline
on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Build and push to local registry
      run: |
        docker build -t localhost:32000/test-nginx:${{ github.run_id }} .
        docker push localhost:32000/test-nginx:${{ github.run_id }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Deploy
      run: |
        kubectl set image -n proj1 deployment/nginx-deployment \
          nginx=localhost:32000/test-nginx:${{ github.run_id }}
        kubectl rollout status -n proj1 deployment/nginx-deployment